steps:
  debug-files:
    name: Debug Files
    image: alpine
    commands:
      - ls -la /woodpecker/src/github.com/wellrcosta/email-service

  deploy-k8s:
    name: Deploy to Kubernetes
    image: lachlanevenson/k8s-kubectl:latest
    volumes:
      - /woodpecker/src:/workspace
    environment:
      KUBECONFIG_CONTENT:
        from_secret: KUBE_CONFIG
    commands:
      - mkdir -p /root/.kube
      - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
      - kubectl cluster-info
      - ls -la /workspace
      - ls -la /workspace/github.com
      - ls -la /workspace/github.com/wellrcosta
      - echo "${CI_REPO_NAME}"
      - cd /workspace/github.com/wellrcosta/${CI_REPO_NAME}
      - kubectl apply -f deployment.yaml