steps:
  - name: Deploy to Kubernetes
    image: lachlanevenson/k8s-kubectl:latest
    environment:
      KUBECONFIG_CONTENT:
        from_secret: KUBE_CONFIG
    commands:
      - mkdir -p /root/.kube
      - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
      - kubectl cluster-info
      - kubectl apply -f deployment.yaml
