steps:
  debug-files:
    name: Debug Files
    image: alpine
    commands:
      - ls

  deploy-with-helm:
    name: Deploy with Helm
    image: alpine/helm:3.8.0
    environment:
      KUBECONFIG_CONTENT:
        from_secret: KUBE_CONFIG
    commands:
      - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
      - helm upgrade --install email-service ./charts