steps:
  - name: Install & Test
    image: node:20
    commands:
      - npm ci
      - npm run test -- --coverage

  - name: Docker Build & Push
    image: woodpeckerci/plugin-kaniko
    settings:
      repo: wellrcosta/email-service
      tags:
        - latest
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_TOKEN
