steps:
  debug-files:
    name: Debug Files
    image: alpine
    commands:
      - ls -la /woodpecker/src/github.com/wellrcosta/email-service

  deploy-k8s:
    name: Deploy to Kubernetes
    image: lachlanevenson/k8s-kubectl:latest
    volumes:
      - /woodpecker/src:/mnt/src  # Mapeia o diretório para outro caminho dentro do container
    environment:
      KUBECONFIG_CONTENT:
        from_secret: KUBE_CONFIG
    commands:
      - mkdir -p /root/.kube
      - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
      - kubectl cluster-info
      - cd /mnt/src/github.com/wellrcosta/email-service
      - ls -la  # Verifica o conteúdo do diretório dentro do container
      - kubectl apply -f Deployment.yaml