steps:
  deploy-k8s:
    name: Deploy to Kubernetes
    image: lachlanevenson/k8s-kubectl:latest
    volumes:
      - /woodpecker/src:/woodpecker/src
    environment:
      KUBECONFIG_CONTENT:
        from_secret: KUBE_CONFIG
    commands:
      - mkdir -p /root/.kube
      - echo "$KUBECONFIG_CONTENT" > /root/.kube/config
      - kubectl cluster-info
      - cd /woodpecker/src/github.com/wellrcosta/email-service
      - ls -la # Verifica os arquivos no diretório
      - chmod -R 755 /woodpecker/src/github.com/wellrcosta/email-service # Garantir permissões
      - kubectl apply -f /woodpecker/src/github.com/wellrcosta/email-service/Deployment.yaml # Aplica o deployment
