steps:
  - name: Docker Build & Push
    image: woodpeckerci/plugin-kaniko
    settings:
      dockerfile: Dockerfile
      context: .
      repo: ${DOCKER_USER}/${CI_REPO_NAME}
      tags:
        - latest
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_TOKEN
