steps:
  - name: Install & Test
    image: node:20
    commands:
      - npm ci
      - npm run test -- --coverage

  - name: debug
  image: alpine
  commands:
    - echo "Docker user: ${DOCKER_USER}"
    - echo "Repo: ${DOCKER_USER}/${CI_REPO_NAME}"

  - name: Docker Build & Push
    image: woodpeckerci/plugin-kaniko
    settings:
      repo: ${DOCKER_USER}/${CI_REPO_NAME}
      tags:
        - latest
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_TOKEN
