pipeline:
  build-and-push:
    image: plugins/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    settings:
      repo: ${DOCKER_USER}/${CI_REPO_NAME}
      tags: latest
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_TOKEN
  when:
    event: push
