version: "3.8"

services:
  app:
    build: .
    container_name: email-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_QUEUE=email-queue
      - RABBITMQ_DLQ_QUEUE=email-dlq
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_HOST=smtp.mailtrap.io
      - SMTP_PORT=587
      - SMTP_USER=your_user
      - SMTP_PASSWORD=your_pass
      - SMTP_FROM=no-reply@example.com
      - MAX_EMAILS_PER_MINUTE=100
      - MAX_RETRIES=3
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
