name: email-service
system: homelab
environment: prod
namespace: default
appVersion: latest

deployment:
  image: wellrcosta/email-service
  tag: latest
  containerPort: 3000
  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

service:
  type: ClusterIP

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

configMaps: [config-map-global, email-service-config]

secrets: [smtp-ses-secret]

envs:
  PORT: 3000
